name: 'Setup UTPM'
description: 'Install and configure UTPM (Unofficial Typst Package Manager)'
author: 'Typst Community'

branding:
  icon: 'package'
  color: 'blue'

inputs:
  version:
    description: 'Version of UTPM to install (e.g., "0.3.0" or "latest")'
    required: false
    default: 'latest'
  
  token:
    description: 'GitHub token for API requests (to avoid rate limiting)'
    required: false
    default: ${{ github.token }}

outputs:
  version:
    description: 'The installed version of UTPM'
  
  cache-hit:
    description: 'Whether the installation was restored from cache'

runs:
  using: 'node20'
  main: 'dist/index.js'
